#!/usr/bin/env sh

set -e


bin_name() {
  printf "the-office-quote"
}

bin_name_full() {
  name="$(bin_name)-$1-$2"

  printf "%s" "$name"
}

bin_name_build() {
  name="$(bin_name)"

  if [ "$1" = "windows" ]; then
    name="$name.exe"
  fi

  printf "%s" "$name"
}

compress_file_name() {
  os="$1"
  arch="$2"
  compress_file_path="$3-$os-$arch"

  if [ "$os" = "windows" ]; then
    compress_file_path="$compress_file_path.zip"
  else
    compress_file_path="$compress_file_path.tar.gz"
  fi

  printf "%s" "$compress_file_path"
}

bin_version() {
  bin_version=$(git tag --sort=-creatordate | head -n 1)
  [ -z "$bin_version" ] && bin_version="dev-build"

  printf "%s" "$bin_version"
}


VERSION="$(bin_version)"
TARGET_OSS="linux|windows|darwin"
TARGET_ARCHS="386|amd64|arm|arm64"
SCRIPT_DIR=$(dirname "$(realpath "$0")")
PROJECT_DIR="$(realpath "$SCRIPT_DIR"/..)"


compile() {
  os="$1"
  arch="$2"
  output_bin="$3"
  bin_version="$4"

  (
    set -x;
    GOOS="$1" GOARCH="$2" go build -ldflags "-s -w -X main.version="$bin_version"" -o "$output_bin"
  )
}

compress_file() {
  file_path="$1"
  file_name="$(basename "$file_path")"
  compress_file_path="$2"
  compress_dir="$3"
  win="$4"

  if [ "$win" = "true" ]; then
    (
      set -x;
      zip -j "$compress_file_path" "$file_path"
    )
  else
    (
      set -x;
      tar -czvf "$compress_file_path" -C "$compress_dir" "$file_name"
    )
  fi
}

checksum_file() {
  file_path="$1"
  file_name="$(basename "$file_path")"
  checksum_file_path="./$file_name.sha256"

  (
    set -x;
    sha256sum "$file_name" > "$checksum_file_path"
  )
}

build() {
  os="$1"
  arch="$2"

  echo "==> Building for $os/$arch"

  win="false"

  if [ "$os" = "windows" ]; then
    win="true"
  fi

  bin_name="$(bin_name)"
  bin_full_name="$(bin_name_full "$os" "$arch")"
  bin_compile_name="$(bin_name_build "$os")"
  compressed_file_name="$(compress_file_name "$os" "$arch" "$bin_name")"

  out_bin_dir="$PROJECT_DIR/.bin/$bin_full_name"
  out_bin_path="$out_bin_dir/$bin_name"
  compress_file_path="$PROJECT_DIR/.bin/$compressed_file_name"

  mkdir -p "$out_bin_dir"

  echo

  echo "=> Compiling for $os/$arch"
  compile "$os" "$arch" "$out_bin_path" "$VERSION"
  echo

  echo "=> Compress $out_bin_path"
  compress_file "$out_bin_path" "$compress_file_path" "$out_bin_dir" "$win"
  echo

  echo "=> Remove $out_bin_dir"
  (set -x; rm -r "$out_bin_dir")
  echo

  echo "=> Checksum for $compress_file_path"
  (cd ./.bin/; checksum_file "$compressed_file_name")
  echo
}

rm -rf ./.bin
mkdir ./.bin

cd "$PROJECT_DIR"

for os_and_arch in $(go tool dist list); do
  os="$(echo $os_and_arch | cut -d "/" -f1)"
  arch="$(echo $os_and_arch | cut -d "/" -f2)"

  if (echo "$os" | grep -qEv "$TARGET_OSS"); then
    continue
  fi

  if (echo "$arch" | grep -qEv "$TARGET_ARCHS"); then
    continue
  fi

  build "$os" "$arch" &
done

wait
