---
name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - name: install deps
        run: go mod download

      - name: check tidy
        run: go mod tidy -diff

      - name: run code checks
        run: |
          echo "Check formatting"
          golangci-lint fmt --diff-colored

          echo "Check linting"
          golangci-lint run
